# # llm:
# #   host: ${LLM_HOST}
# #   model: ${LLM_MODEL}
# llm_grpc:
#   host: ${LLM_GRPC_HOST}
#   port: ${LLM_GRPC_PORT}
#   model: ${LLM_GRPC_MODEL}
grpc:
  host: "0.0.0.0"
  port: 50051
gateway:
  host: "0.0.0.0"
  port: 8080