version: "3.8"

services:
  grpc_server:
    build: .
    container_name: grpc_server
    ports:
      - "50051:50051"
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
